_BASE_: "../Pascal/base.yaml"
MODEL:
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1203
    NAME: "ScoreOutputROIHeads"
    SCORE_THRESH_TEST: 0.0001
  RESNETS:
    DEPTH: 50
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000  # 180000 * 16 / 100000 ~ 28.8 epochs
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001