_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  WEIGHTS: ""
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_resnet"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
    NAME: "ScoreOutputROIHeads"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval',)
  TEST: ('voc_2007_test', 'comic_2012_val', 'clipart_2012_test', 'water_2012_test', )
SOLVER:
  STEPS: (50000, 70000)
  MAX_ITER: 80000  # 17.4 epochs
  BASE_LR: 0.0025
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 500
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 0
