_BASE_: "base.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  FPN:
    NAME: "NASFPN"
  WEIGHTS: ""
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  SWSL: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_resnet"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
    NAME: "ScoreOutputROIHeads"

